app = "unet-bg-remover"  # Replace with your Fly.io app name

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  # Set environment variables here if needed

[build]
  # You can specify build args or builder if needed

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
