app = "unet-bg-remover"
primary_region = "waw"

[build]

[env]
PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false         # ✅ FIX: Prevent Fly.io from stopping machines
  auto_start_machines = true
  min_machines_running = 1           # ✅ FIX: Keep at least one machine running
  processes = ["app"]

[checks]
  [checks.http]
    interval = "10s"
    timeout = "5s"
    method = "get"
    path = "/health"                 # ✅ Health check route
    grace_period = "20s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
