app = "unet-bg-remover"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 4096
