app = "unet-bg-remover"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = 10000       # 10 seconds
    timeout = 2000         # 2 seconds
    grace_period = 5000    # 5 seconds delay before health checks start
    method = "GET"
    path = "/"
    tls_skip_verify = true
